#Requires -Version 5.1
<#
.SYNOPSIS
  Convert markdown to a styled PDF via Microsoft Edge headless printing.

.PARAMETER MarkdownPath
  Absolute or relative path to the markdown file.

.PARAMETER PdfPath
  Absolute or relative output path for the PDF.

.PARAMETER HeaderLabel
  Optional short label shown in the report header.

.PARAMETER LogoPath
  Optional path to a logo image (svg/png/jpg) to show in the header.
#>
param(
    [Parameter(Mandatory = $true)]
    [string] $MarkdownPath,

    [Parameter(Mandatory = $true)]
    [string] $PdfPath,

    [Parameter(Mandatory = $false)]
    [string] $HeaderLabel = "Git Activity Report",

    [Parameter(Mandatory = $false)]
    [string] $LogoPath
)

$ErrorActionPreference = "Stop"
$DefaultBrandAssetsDir = "C:\Users\OmarElsahy\Scopedx Dropbox\Omar Elsahy\Logo assets"

function Get-EdgePath {
    $candidates = @(
        "${env:ProgramFiles}\Microsoft\Edge\Application\msedge.exe",
        "${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe"
    )
    foreach ($p in $candidates) {
        if (Test-Path -LiteralPath $p) { return $p }
    }
    return $null
}

function Resolve-BrandAsset {
    param(
        [string] $BrandAssetsDir,
        [string[]] $RelativeCandidates
    )
    if ([string]::IsNullOrWhiteSpace($BrandAssetsDir) -or -not (Test-Path -LiteralPath $BrandAssetsDir)) {
        return $null
    }
    foreach ($candidate in $RelativeCandidates) {
        $full = Join-Path $BrandAssetsDir $candidate
        if (Test-Path -LiteralPath $full) {
            return (Resolve-Path -LiteralPath $full).Path
        }
    }
    return $null
}

function Build-ReportHtml {
    param(
        [string] $BodyHtml,
        [string] $HeaderText,
        [string] $ResolvedLogoPath
    )
    $logoTag = ""
    if ($ResolvedLogoPath) {
        $logoUri = ([System.Uri]$ResolvedLogoPath).AbsoluteUri
        $logoTag = "<img class=""brand-mark"" src=""$logoUri"" alt=""Logo""/>"
    }

    @"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Git Activity Report</title>
<style>
  :root {
    --brand-navy: #21005f;
    --brand-blue: #024cc1;
    --brand-cyan: #10a6f8;
    --ink: #1a1f36;
    --muted: #59607a;
    --surface: #f7f9ff;
    --line: #d9e0f2;
  }
  @page { size: A4; margin: 0.75in; }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    font-family: "Segoe UI", Arial, sans-serif;
    font-size: 10.5pt;
    color: var(--ink);
    line-height: 1.45;
  }
  .report-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    border-bottom: 2px solid var(--brand-blue);
    padding-bottom: 12px;
    margin-bottom: 16px;
  }
  .header-meta {
    max-width: 70%;
  }
  .brand-chip {
    display: inline-block;
    background: linear-gradient(90deg, var(--brand-blue), var(--brand-cyan));
    color: #fff;
    border-radius: 999px;
    padding: 4px 10px;
    font-size: 9pt;
    font-weight: 700;
    margin-bottom: 8px;
    letter-spacing: 0.02em;
  }
  .label {
    display: inline-block;
    color: var(--brand-navy);
    font-size: 14pt;
    font-weight: 700;
  }
  .brand-mark {
    display: block;
    max-height: 108px;
    max-width: 460px;
    width: auto;
    object-fit: contain;
  }
  h1, h2, h3, h4 {
    color: var(--brand-navy);
    margin-top: 1.1em;
    margin-bottom: 0.45em;
    page-break-after: avoid;
  }
  h1 { border-bottom: 1px solid var(--line); padding-bottom: 6px; }
  code {
    background: #eef3ff;
    border: 1px solid #d8e3ff;
    border-radius: 4px;
    padding: 0.05rem 0.28rem;
    font-family: Consolas, "Courier New", monospace;
    font-size: 0.94em;
  }
  pre {
    background: #10162c;
    color: #edf1ff;
    border-radius: 8px;
    padding: 12px;
    overflow-x: auto;
  }
  pre code { background: transparent; border: 0; color: inherit; padding: 0; }
  table {
    width: 100%;
    border-collapse: collapse;
    margin: 10px 0 14px;
    font-size: 9.8pt;
  }
  th {
    background: linear-gradient(90deg, #f0f6ff, #f8fbff);
    text-align: left;
    border: 1px solid var(--line);
    padding: 8px 10px;
  }
  td {
    border: 1px solid var(--line);
    padding: 8px 10px;
    vertical-align: top;
  }
  tr:nth-child(even) td { background: #fbfdff; }
  .trello-recent {
    color: var(--brand-blue);
    font-weight: 700;
  }
  .trello-total {
    color: var(--muted);
    font-weight: 500;
  }
  hr { border: 0; border-top: 1px solid var(--line); margin: 16px 0; }
  .report-footer {
    margin-top: 18px;
    border-top: 1px solid var(--line);
    color: var(--muted);
    font-size: 8.8pt;
    padding-top: 8px;
  }
</style>
</head>
<body>
  <header class="report-header">
    <div class="header-meta">
      <span class="brand-chip">SCOPE-Dx Activity Reporting</span><br/>
      <span class="label">$HeaderText</span>
    </div>
    $logoTag
  </header>
  <main>
$BodyHtml
  </main>
  <footer class="report-footer">Generated by Git Activity Report Tool.</footer>
</body>
</html>
"@
}

$MarkdownPath = (Resolve-Path -LiteralPath $MarkdownPath).Path
$PdfPath = [System.IO.Path]::GetFullPath($PdfPath)
$pdfDir = Split-Path -Parent $PdfPath
if (-not (Test-Path -LiteralPath $pdfDir)) {
    New-Item -ItemType Directory -Path $pdfDir -Force | Out-Null
}

$bodyHtmlPath = Join-Path $env:TEMP ("git-report-body-" + [Guid]::NewGuid().ToString("n") + ".html")
$fullHtmlPath = Join-Path $env:TEMP ("git-report-" + [Guid]::NewGuid().ToString("n") + ".html")

try {
    $bodyHtml = $null
    $pandoc = Get-Command pandoc -ErrorAction SilentlyContinue
    if ($pandoc) {
        & pandoc $MarkdownPath -f markdown -t html -o $bodyHtmlPath
        if ($LASTEXITCODE -ne 0) { throw "pandoc failed with exit code $LASTEXITCODE" }
        $bodyHtml = Get-Content -LiteralPath $bodyHtmlPath -Raw -Encoding UTF8
    }
    else {
        $escaped = [System.Net.WebUtility]::HtmlEncode((Get-Content -LiteralPath $MarkdownPath -Raw -Encoding UTF8))
        $bodyHtml = "<pre>$escaped</pre>"
    }

    $resolvedLogo = $null
    if ($LogoPath -and (Test-Path -LiteralPath $LogoPath)) {
        $resolvedLogo = (Resolve-Path -LiteralPath $LogoPath).Path
    }
    if (-not $resolvedLogo) {
        $resolvedLogo = Resolve-BrandAsset -BrandAssetsDir $DefaultBrandAssetsDir -RelativeCandidates @(
            "Logo files\PNGs - SVGs\SVG\Asset 1.svg",
            "Logo files\PNGs - SVGs\SVG\Asset 2.svg",
            "Logo files\SVG\Logo-1.svg",
            "Logo files\SVG\Logo-2.svg"
        )
    }

    $html = Build-ReportHtml -BodyHtml $bodyHtml -HeaderText $HeaderLabel -ResolvedLogoPath $resolvedLogo
    Set-Content -LiteralPath $fullHtmlPath -Value $html -Encoding UTF8

    $edge = Get-EdgePath
    if (-not $edge) { throw "Microsoft Edge not found in standard install locations." }

    if (Test-Path -LiteralPath $PdfPath) {
        Remove-Item -LiteralPath $PdfPath -Force
    }

    $uri = ([System.Uri]$fullHtmlPath).AbsoluteUri
    $args = @(
        "--headless",
        "--disable-gpu",
        "--no-pdf-header-footer",
        "--print-to-pdf=$PdfPath",
        $uri
    )
    $p = Start-Process -FilePath $edge -ArgumentList $args -Wait -PassThru -NoNewWindow
    if ($p.ExitCode -ne 0) { throw "Edge print-to-pdf exited with code $($p.ExitCode)" }
    if (-not (Test-Path -LiteralPath $PdfPath)) { throw "PDF was not created at $PdfPath" }
}
finally {
    if (Test-Path -LiteralPath $bodyHtmlPath) { Remove-Item -LiteralPath $bodyHtmlPath -Force -ErrorAction SilentlyContinue }
    if (Test-Path -LiteralPath $fullHtmlPath) { Remove-Item -LiteralPath $fullHtmlPath -Force -ErrorAction SilentlyContinue }
}

Write-Host "Wrote PDF: $PdfPath"

